inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'

Style/WordArray:
  MinSize: 3

Style/SymbolArray:
  MinSize: 3

Style/AndOr:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '()'
    '%w': '()'
    '%W': '()'

Layout/DotPosition:
  EnforcedStyle: trailing

Style/RedundantReturn:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal
